#! /bin/bash
_cdw()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=$(ls -d / $PATH_CDW*/ | xargs -n1 basename)

    if [[ -z "${cur}"  ]] ; then
       COMPREPLY=( $opts )
       return 0
    else
       COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
       return 0
    fi
}
complete -F _cdw cdw
